### PR TITLE
CORE-1820 Forms asset updates

### PR DESCRIPTION
**Pull request by MarkDKoslow**
[CORE-1820](https://lambdaschool.atlassian.net/browse/CORE-1820)

## Description
Update logo and favicon

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by mellogarrett** [comment]
We should go ahead and remove the old icon/logo files as well. 

Are there color updates that need to be made as well? I believe the red has changed.

**Comment by MarkDKoslow** [comment]
Oh weird, I deleted the old icon/logo locally... not sure why that's not showing up here.

And good call about the colors 👍

**Comment by MarkDKoslow** [comment]
@mellogarrett If you click "show rich diff" next to the logo, you can see the old one was deleted. Not sure why the same isn't true for the favicon 🤔

**Comment by mellogarrett** [comment]
Oh nice. Yea, that's weird about the image deletions

**Pull request merged**
